### ISSUE TITLE
Evaluate two themes to determine how to proceed

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#45]
Please review this theme and can go to the "Live Preview" link to see the actual HTML layout page

https://themeforest.net/item/ubergrid-responsive-grid-wordpress-theme/6383212

Please review the implications of this such as:

- Does this like an acceptable starting layout (can review source code). Does it seem well enough coded with not any weird things that may make it hard to use?

- Would it be possible to easily modify the number (such as having less or more of these than appear in the demo) of elements (the boxes / rectangles that have images and text) that are used without making major changes to the layout?

- There are different types of elements, we would want to modularize the way these are rendered, such as having a separate PHP class that holds logic for each element type and this code would be re-used to render this element each time (as we would define the different element types in the google sheet, similar to the livre-4 layout). Would this present any issues, such as the layout being poorly coded or done in a weird way that would make this difficult?

**Comment by cyberdypro** [comment]
@stacksavings 
- This layout doesn't any different with what we do for now
- As my sheet in #46, we still easy for create multi grid element. Each grid element is a row in sheet with different type
- As our solution in #46, each element has single PHP sub-class so we can easy for create new element.
