### ISSUE TITLE
Planning modularity, containers within layout

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#46]
This relates to https://github.com/StackSavingsTeam/googlesheetslayout/issues/45

The idea that I have is that we can identify sections of a layout, for example, in the above layout (when checking "Live preview" there are only two main areas of the page (when viewed in Desktop mode), one is the menu on the left side and the other is the grid area that has all the grid elements.

An example of what I would want to do is to create a PHP class / module that is a "grid container" so that it is separated from the main layout code. Everything needed for the grid should be located here (possible having css and javascript files included within this module. Then, the main layout would just include this module wherever it wants to show a grid, therefore, the grid isn't tied to being in a specific place. If, for example, we wanted to put this grid into another layout in the future, then we could easily.

This grid module would then use separate PHP sub-modules for each element type, so that each element type is defined in it's own sub-module.

Within the Google sheet, there would be a column that indicates which module an element is part of and then another column that indicates it's type of element. Then, the third column (which is the column we now have for field name) would be there also that indicates specific values.

**Comment by stacksavings** [comment]
@cyberdypro Please review above and give your feedback, I am just putting my thoughts together on this but want to plan it out well so that we build it in a way that is optimal for long-term use.

**Comment by cyberdypro** [comment]
@stacksavings I think idea that about create sub-classs for each grid element is good. For sheet data I have created a sample sheet at [here](https://docs.google.com/spreadsheets/d/1t3PCOY9ZGyokZBjpmTG2U61fO4zcSETsGDHMHRiZujY/edit?usp=sharing). Basically, we still have the same sheet with another sheet, but we will add some addtional column. At my sheet, you can see the `Type` column, if any row have value for this column it should be a Grid element. We can use type for make Grid element by PHP sub-class (like GridImage, GridVideo, GridEmbed). With each module we can use the remaining columns (image, embed, title, description, additional data) for get data that used to rendered the grid element. E.g: with image type we just use `image`, `title`, `description` for create GridImage in layout. How do you think ? 

Please advise.
Thanks,
