### ISSUE TITLE
Video convert from H265 to H264

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/StackSavings-Layouts#49]
Need to convert h265 file https://drive.google.com/file/d/0B7z8y6r0T33xdE1lUmJ4dWVIaEk/view?usp=sharing

**Comment by avi-stacksavings** [comment]
tried with adobe premiere, but its not showing video.. just showing blank blank screen with audio... checking codecs for premiere 
@stacksavings

**Comment by stacksavings** [comment]
@avi-stacksavings  This is a bad approach, you have not put any info here that is useful such as where you posted asking question on this. Always put links etc, this just seems like nothiing being done as far as I can tell.

**Comment by stacksavings** [comment]
@avi-stacksavings  there are lot of Google results on this, exactly what you are trying? This is seeming like "Will do later" type of approach on this and is concerning as I was going to use some footages in something I am trying so this is delaying things needlessly.

**Comment by avi-stacksavings** [comment]
Obviously I checked those "google results" already and tried downloading the software they were providing.. installer was adding bunch of unnecessary "installer" and didnt actually install any software
tried this: http://video-help.over-blog.com/2015/10/convert-h-265-hevc-to-h-264-for-easier-playback.html
https://sourceforge.net/projects/h-265-to-h-264-converter/
https://www.youtube.com/watch?v=rYa4sdAU9eM


One guy FB replied with to import on adobe premiere and then render video in .h264
https://www.facebook.com/groups/sanjayfgupta/
post is in there but couldnt get URL of my post as it just shows group URL when i open post in group
@stacksavings

**Comment by avi-stacksavings** [comment]
Found an android converter
converted file: https://drive.google.com/open?id=0B48hPIRjv_ZJempDMkM5WW1BdE0

app used Adobe premiere clip for mobile: https://play.google.com/store/apps/details?id=com.adobe.premiereclip&hl=en
@stacksavings

**Comment by stacksavings** [comment]
Try posting on other forums then and post links here...

⁣Sent from BlueMail ​

**Comment by stacksavings** [comment]
Ok please try this and report if works

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
yea it worked on camtasia.
@stacksavings

**Comment by stacksavings** [comment]
@avi-stacksavings  have you fully documented this in our sheets for future reference?
