### ISSUE TITLE
Research on royalty free videos

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/StackSavings-Layouts#50]
Check for royalty free videos website and look for Sacramento videos

**Comment by avi-stacksavings** [comment]
Through research I found these websites which provides mostly free videos:
https://videos.pexels.com/
https://pixabay.com/

Other through google search i found some but they dont have free videos:
https://www.shutterstock.com/video/?kw=royalty%20free%20videos&gclid=Cj0KEQjwuOHHBRDmvsHs8PukyIQBEiQAlEMW0C-Mr8PRRyygVV5q-eJBG-PpoCMNyMB9rSaDeYude1MaAgZu8P8HAQ&gclsrc=aw.ds&dclid=CPKYr7LAs9MCFVQvjgodXQgECg

https://www.videoblocks.com/video/sacramento-skyline-at-blue-hour-v_wwja6t_lijsmuot3/
https://www.dvarchive.com/search-results.aspx?q=sacramento&p=1&type=keyword

Still looking more @stacksavings

**Comment by stacksavings** [comment]
What about other cities like I mentioned? Also check that able to actually download footage for free and that it has no watermark. Some sites that give results say it's royalty free but then ask for payment when trying to get footage

**Comment by avi-stacksavings** [comment]
found basic videos with like traffic time lapse, or office working with blurred look.
not for cities like boston , california etc

**Comment by stacksavings** [comment]
the info we gained is enough for now.

@avi-stacksavings  make sure the info for this is documented in one of our sheets.

Comment here to acknowledge then I can close.
