### ISSUE TITLE
Marketing - Account creations

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#52]
Check in the "Account logins" sheet where we have secure info.

Need to find this section:

**Item posting info to use for accounts:**

Use info there to create accounts for each under **Accounts to create(either website or android app, if not url then assume its app you need to install).**

Get accounts fully activated and ready so we can start posting ads there.

**Comment by stacksavings** [comment]
Make sure to add login info in account logins sheet for each app that you create an account for.

**Comment by stacksavings** [comment]
Please also get this app: zip recruiter

And add info on sheet, see if can then post some basic job on this like for marketing person just to see if it works to actually post for free.

**Comment by avi-stacksavings** [comment]
@stacksavings  added comments in Login sheet...

For Zip recruiter, its not available in my region. I mean its not showing in my play store at all. I think coz of Region

**Comment by stacksavings** [comment]
Yes I thought this kind of stuff may happen.. can you look at virtual Android options like one one or something

⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
i found this one.. but couldnt find cracked one. 
https://www.genymotion.com/

@stacksavings

**Comment by avi-stacksavings** [comment]
@stacksavings Install this on android tablet.

https://play.google.com/store/apps/details?id=com.sand.airdroid&hl=en

let me know once done, i am checking how i can connect from here.

**Comment by stacksavings** [comment]
@avi-stacksavings  I will have more work on this starting today. Please comment here to acknowledge and then I can update with this info.

**Comment by avi-stacksavings** [comment]
@stacksavings okay
