### ISSUE TITLE
Tech-solution: Implement widget in Testimonial section

### ISSUE THREAD

**Issue by avi-stacksavings** [StackSavingsTeam/StackSavings-Layouts#54]
USe "tech-solution" layout (folder name is tech-solution) from the workspace. and implement widget in testimonial section as its implemented in Livre-4

Worksapce name in c9: googlesheet-layouts-aymen

**Comment by stacksavings** [comment]
@avi-stacksavings please have work start on this

**Comment by stacksavings** [comment]
@avi-stacksavings  you seem off project fully as not paying attention in these? what is going on

**Comment by avi-stacksavings** [comment]
@stacksavings He made a Pull request on this and you mentioned in comment that you will review. Please #59 created by Pull request.

**Comment by stacksavings** [comment]
@avi-stacksavings  I am not asking you about what he was doing, I am commenting on what you are doing. We have a process for testing and it needs to be followed. 

Please review the following to be more clear for this and any other tickets:

1) If the ticket was ready for verification then you are supposed to verify on both c9 and then FTP.

2) You are supposed to put full verification info here always.

3) When I say I will review that does not mean that you do not test. It has nothing to do with this. I am referring to code review which is independent of your testing. Your testing has to be done on every ticket unless it explicitly states in the ticket that it is not needed.

**Comment by stacksavings** [comment]
@avi-stacksavings start doing your job if you want to continue. I clearly left info above what you need to do and yet you are still endlessly stalling.

**Comment by stacksavings** [comment]
@avi-stacksavings avi, your communication hugely lacking, you are supposed to update if you are late with things, say what you are doing etc

**Comment by stacksavings** [comment]
@FroyoAndroid your changes are wrong, you are supposed to just use the testimonial the same way as in the other layout, you created a new tpl file instead, this is wrong, need to fix.

@avi-stacksavings  keep testing though his last changes

**Comment by avi-stacksavings** [comment]
@stacksavings testing on mobile now.

**Comment by avi-stacksavings** [comment]
@stacksavings 
Tested on http://servicejoin.com/tech-solution/
Sheet used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=893871282
Tab used: tech-solution_testimonial

Working fine on both desktop and mobile browser.

**Comment by stacksavings** [comment]
ok he is making more changes so need to re-open though and re-test after these.

**Comment by FroyoAndroid** [comment]
@stacksavings @avi-stacksavings the template file from tech-solution folder has been removed.
no it uses the template file which is present in the widget section.
Please review the changes.

**Comment by avi-stacksavings** [comment]
Widget section broken in mobile
Check this screenshot
![screenshot_20170511-002834](https://cloud.githubusercontent.com/assets/20572760/25916013/e9daccc4-35e0-11e7-85c7-38ba573149c5.png)

**Comment by avi-stacksavings** [comment]
Niraj please check above screenshot

**Comment by FroyoAndroid** [comment]
checked css issue need to be handled by css guy

**Comment by avi-stacksavings** [comment]
@FroyoAndroid in your last fix, this CSS issue wasnt there. you need to check what went wrong and need to fix it.

**Comment by FroyoAndroid** [comment]
you meant livre-4 template

**Comment by stacksavings** [comment]
Ok wait I will talk to Niraj

**Comment by avi-stacksavings** [comment]
@stacksavings  Niraj working on CSS part to make it like ttp://servicejoin.com/tech-solution/

**Comment by avi-stacksavings** [comment]
@stacksavings 
tested using these URLs
http://servicejoin.com/tech-solution/
servicejoin.com/livre-4/index.php

Shee used: https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=893871282

Both working fine.
