### ISSUE TITLE
Implement another widget that is clone of testimonial

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#58]
Implement another widget that is a clone of the testimonial widget and then use this in another layout. You should then make a few minor tweaks in this widget HTML code so it's obvious that it is different.

This widget can be called "items" instead of Testimonial. Make new entries in Google sheet that this uses also.

The point of this is to test having a second widget to make sure it works. Then I'm going to have more changes to customize this widget more after this.

**Comment by stacksavings** [comment]
@avi-stacksavings ????

**Comment by avi-stacksavings** [comment]
@stacksavings Niraj started working on this already. He will update once finished.

**Comment by stacksavings** [comment]
@FroyoAndroid Please comment here when starting a ticket and also once it is resolved and ready for verification. It is important to always do this.

**Comment by avi-stacksavings** [comment]
@FroyoAndroid 
In this sheet it says "testimonial" in C column for existing widget, but for another widget you will be making use "item"  as type or "item-widget" in C column

https://docs.google.com/spreadsheets/d/1HBZybnUJOdUokHZIU_dPeK1-2xhT3u5yAoH911cuij4/edit#gid=893871282

**Comment by avi-stacksavings** [comment]
@stacksavings Niraj started, as he have a day job too.. will continue at 7:30 am your time

**Comment by FroyoAndroid** [comment]
https://layout-amit-stacksavings.c9users.io/item-test/index.php
DONE Implementation

**Comment by FroyoAndroid** [comment]
Please review

**Comment by avi-stacksavings** [comment]
@stacksavings @FroyoAndroid  I didnt understand whats done
https://layout-amit-stacksavings.c9users.io/item-test/index.php

@stacksavings I dont think this is what you have asked?
