### ISSUE TITLE
new layout clone

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#60]
clone these two layout pages:

https://www.outdoorproject.com/blog-news/californias-best-backpacking-trips
https://www.outdoorproject.com/blog-news/californias-best-backpacking-trips

These should be cloned into one layout, not two separate ones, but would be a different page within that layout.

**Comment by stacksavings** [comment]
@avi-stacksavings please do this as top priority and get it checked in after testing. 

- If dev needs to do anything like URL path renaming then pass the ticket along to them after you check in your changes and assign to them to do that part. Make sure things are fully clear to the dev by putting any needed info here in this ticket.

**Comment by avi-stacksavings** [comment]
@stacksavings Above both layout pages are same (even same URL)
you sure its correct?

**Comment by stacksavings** [comment]
Ok hold off I will check, they may not have different URLs for each page


⁣Sent from BlueMail ​

**Comment by avi-stacksavings** [comment]
@stacksavings Haven't started yet, as asked to hold off in last comment.
