### ISSUE TITLE
Evaluate layout pages

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#61]
Pleas check the layout pages mentioned here:

https://github.com/StackSavingsTeam/googlesheetslayout/issues/60

@FroyoAndroid  please evaluate the HTML code on this and any libraries used, we want to see about implementing similar functionality as the galleries in those two pages. 

Please start thinking on this, if you want to use some JavaScript library or something we can do that but please put any info here initially so I can review.

Thanks

**Comment by stacksavings** [comment]
@avi-stacksavings  please have @FroyoAndroid  start checking on this and make sure updates are left here.

**Comment by avi-stacksavings** [comment]
@stacksavings  As #60 is on hold currently. no updates on same
