### ISSUE TITLE
Create Facebook login widget from existing Facebook login code

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#62]
Please refer to both of these links:

https://github.com/StackSavingsTeam/StackSavings-Layouts/wiki/Getting-Started
https://github.com/StackSavingsTeam/StackSavings-Layouts/wiki/Widget-Structure

We have a Facebook login button that writes data from the user that clicks the button (such as name, gender, etc) to a Google Sheet. This was working at one point but I think is currently broken. This was put in place before we started using widgets. We need to make this into a widget and then also fix it so it is working properly.

In livre-4/index.php, you can find this code and then follow from there where $facebookIntergration is used to get an idea of how it is currently implemented.

$facebookIntergration = FacebookIntegration::getInstance('357318791277486', 'facebook-logins')->setLoginCallback('facebook_login');
?>

**Comment by ved16sep** [comment]
Facebook login was breaking due to incorrect redirect domain, I have added a new domain https://layout-amit-stacksavings.c9users.io/ to Domain Manager in our facebook API.

**Comment by ved16sep** [comment]
Facebook login was breaking due to incorrect redirect domain, I have added a new domain https://layout-amit-stacksavings.c9users.io/ to Domain Manager in our facebook API.

**Comment by aamirsatti** [comment]
Message For Rick @stacksavings .
Hi Rick ,
I want to know why you do this to me ? 
If you had any problem with my work then why didn't you told me ?
Why you blocked me ? and not replied me from last month ?

**Comment by FroyoAndroid** [comment]
For any new template addition, modifications are required in Quickstart.php file as per the need.

**Comment by avi-stacksavings** [comment]
@kuljeetbabber there is white space issue in css 
check url: https://testing-avi-stacksavings.c9users.io/livre-4/

**Comment by FroyoAndroid** [comment]
Fixed

**Comment by avi-stacksavings** [comment]
@stacksavings 
Issue fixed

Test URL: http://servicejoin.com/livre-4/index.php

**Comment by stacksavings** [comment]
Thanks I will try to review soon.
