### ISSUE TITLE
Implement module of 360 image viewer 

### ISSUE THREAD

**Issue by stacksavings** [StackSavingsTeam/StackSavings-Layouts#63]
**We have existing code in place at:**

https://github.com/StackSavingsTeam/StackSavings-Layouts/blob/master/demo-360/connect.stacksavings.com/fall-activities-to-do-1/index.html

Note, you can also view this live on the web as a demo at:

http://servicejoin.com/demo-360/connect.stacksavings.com/fall-activities-to-do-1/index.html

The task is to extract just the HTML, CSS and JavaScript code that runs the 360 degree image viewer (which is made with the JavaScript Pannellum library) and to make this into a widget within our existing framework so that this can easily be included in other layouts. 

The initial work is just to pull this out into a widget, then we can have another ticket to further refine and make parts of this editable from a Google Sheet.

**Please note that all widgets are located under the directory:**

https://github.com/StackSavingsTeam/StackSavings-Layouts/tree/master/vendor/stacksavings/widgets

**We want to make this into a module similar how this was done for the facebook widget in:**

https://github.com/StackSavingsTeam/StackSavings-Layouts/issues/62

Also this would be similar to how the Testimonial widget was also implemented.

**Comment by stacksavings** [comment]
Please refer to this repo also it may have cleaner code for the 360 image viewer JavaScript module

https://bitbucket.org/stacksavings/stacksavings-360/src

**Comment by FroyoAndroid** [comment]
I have started looking into this issue.
I have completed first part of this issue: 
**The task is to extract just the HTML, CSS and JavaScript code that runs the 360 degree image viewer (which is made with the JavaScript Pannellum library)**

Demo Link: https://image-viewer-test-stacksavings.c9users.io/index.html

**Comment by stacksavings** [comment]
Once basic widget in place please commit changes.

Then just need to make it so that image URL can be edited in sheet

**Comment by FroyoAndroid** [comment]
@stacksavings This issue is on hold as per the discussion.

**Comment by stacksavings** [comment]
I will update this within a few days with next steps.

**Comment by stacksavings** [comment]
Cancelled
